### ISSUE TITLE
What do you think of this algorithm?

### ISSUE THREAD

**Issue by felixorbit** [SteinarLaenen/NC_LOA#1]
Hi, I'm learning optimization algorithm recently.  I read this paper and found it very complicated. Can you tell me how the algorithm works? What do you think of this algorithm?  How does it compare with PSO or other EAs? Thanks.

**Comment by SteinarLaenen** [comment]
Hi! We found it very slow and it was quite complicated to implement. We implemented this algorithm for a course and we tried to reproduce their results, but we failed. If you like I can maybe share the report that we wrote with you? There we go into more details into why we think it did not work.

**Comment by felixorbit** [comment]
Thank you very much. I learned intelligent optimization to complete an assignment, but I've given up these amazing algorithms.
